### Word Embedding Techniques using Embedding Layer in Keras

In [39]:
### Libraries USed Tensorflow> 2.0  and keras

In [2]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
### Vocabulary size
voc_size=10000

#### One Hot Representation

In [6]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[7795, 2131, 1146, 3717], [7795, 2131, 1146, 914], [7795, 5301, 1146, 9819], [1837, 1455, 3534, 5148, 116], [1837, 1455, 3534, 5148, 7675], [4516, 7795, 6867, 1146, 5024], [8041, 3210, 7193, 5148]]


### Word Embedding Represntation

In [7]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 7795 2131 1146 3717]
 [   0    0    0    0 7795 2131 1146  914]
 [   0    0    0    0 7795 5301 1146 9819]
 [   0    0    0 1837 1455 3534 5148  116]
 [   0    0    0 1837 1455 3534 5148 7675]
 [   0    0    0 4516 7795 6867 1146 5024]
 [   0    0    0    0 8041 3210 7193 5148]]


In [10]:
dim=10


In [11]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [13]:
print(model.predict(embedded_docs))

1/1 [==============================] - 4s 4s/step
[[[-1.78534277e-02  4.67050560e-02  2.06121057e-03 -1.78907402e-02
    1.76360942e-02  2.72740386e-02  4.85989563e-02 -2.63094660e-02
    4.41537015e-02 -3.96689028e-03]
  [-1.78534277e-02  4.67050560e-02  2.06121057e-03 -1.78907402e-02
    1.76360942e-02  2.72740386e-02  4.85989563e-02 -2.63094660e-02
    4.41537015e-02 -3.96689028e-03]
  [-1.78534277e-02  4.67050560e-02  2.06121057e-03 -1.78907402e-02
    1.76360942e-02  2.72740386e-02  4.85989563e-02 -2.63094660e-02
    4.41537015e-02 -3.96689028e-03]
  [-1.78534277e-02  4.67050560e-02  2.06121057e-03 -1.78907402e-02
    1.76360942e-02  2.72740386e-02  4.85989563e-02 -2.63094660e-02
    4.41537015e-02 -3.96689028e-03]
  [ 1.04719177e-02 -2.45281942e-02  4.48060669e-02  4.57889326e-02
    2.97913216e-02 -2.16447189e-03  2.83919834e-02  2.92300694e-02
    1.70938410e-02  2.91879661e-02]
  [-5.42791933e-03  3.20195816e-02  4.26522978e-02 -7.35068321e-03
    3.23667862e-02  2.68630646e-0

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 7795, 2131, 1146, 3717])

In [15]:
print(model.predict(embedded_docs)[0])

1/1 [==============================] - 0s 35ms/step
[[-0.01785343  0.04670506  0.00206121 -0.01789074  0.01763609  0.02727404
   0.04859896 -0.02630947  0.0441537  -0.00396689]
 [-0.01785343  0.04670506  0.00206121 -0.01789074  0.01763609  0.02727404
   0.04859896 -0.02630947  0.0441537  -0.00396689]
 [-0.01785343  0.04670506  0.00206121 -0.01789074  0.01763609  0.02727404
   0.04859896 -0.02630947  0.0441537  -0.00396689]
 [-0.01785343  0.04670506  0.00206121 -0.01789074  0.01763609  0.02727404
   0.04859896 -0.02630947  0.0441537  -0.00396689]
 [ 0.01047192 -0.02452819  0.04480607  0.04578893  0.02979132 -0.00216447
   0.02839198  0.02923007  0.01709384  0.02918797]
 [-0.00542792  0.03201958  0.0426523  -0.00735068  0.03236679  0.02686306
   0.00591658  0.0317999   0.02599244  0.02458501]
 [ 0.04537076 -0.00788844  0.04405918 -0.04966495  0.02028764 -0.01938152
  -0.00316383  0.04714579  0.02502084 -0.04618514]
 [ 0.04427898  0.03914685  0.00541358  0.00799819  0.03725232 -0.04558325

In [17]:
print(model.predict(embedded_docs)[1])

1/1 [==============================] - 0s 40ms/step
[[-0.01785343  0.04670506  0.00206121 -0.01789074  0.01763609  0.02727404
   0.04859896 -0.02630947  0.0441537  -0.00396689]
 [-0.01785343  0.04670506  0.00206121 -0.01789074  0.01763609  0.02727404
   0.04859896 -0.02630947  0.0441537  -0.00396689]
 [-0.01785343  0.04670506  0.00206121 -0.01789074  0.01763609  0.02727404
   0.04859896 -0.02630947  0.0441537  -0.00396689]
 [-0.01785343  0.04670506  0.00206121 -0.01789074  0.01763609  0.02727404
   0.04859896 -0.02630947  0.0441537  -0.00396689]
 [ 0.01047192 -0.02452819  0.04480607  0.04578893  0.02979132 -0.00216447
   0.02839198  0.02923007  0.01709384  0.02918797]
 [-0.00542792  0.03201958  0.0426523  -0.00735068  0.03236679  0.02686306
   0.00591658  0.0317999   0.02599244  0.02458501]
 [ 0.04537076 -0.00788844  0.04405918 -0.04966495  0.02028764 -0.01938152
  -0.00316383  0.04714579  0.02502084 -0.04618514]
 [ 0.00549738  0.01803099 -0.04821337  0.0094474  -0.00137913 -0.00977259